### ISSUE TITLE
[PE-D] Incorrect Format of the output for all the employee functions

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-4/tp#77]
The format of the output I am getting for all the "employee" functions does not match with the output displayed in the user guide.

For example, for "add-employee" function,

UG output: 

![image.png](https://raw.githubusercontent.com/madhanse/ped/main/files/f361f1d2-0b20-47ea-8d46-d8a3c8234c2f.png)

Output in my console:

![image.png](https://raw.githubusercontent.com/madhanse/ped/main/files/f15e6f38-4bb7-4c8d-bf40-2c1b88c39df4.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: madhanse/ped#1

**Comment by kairoskoh** [comment]
I believe the reason for the issue is caused by the use of outdated release jar file.
![image](https://user-images.githubusercontent.com/70124507/140601196-40fd9123-2248-4824-9fd5-27187d8383ef.png)
